"""relationship shows and venue 8

Revision ID: 28a863470a67
Revises: b8b315b2018a
Create Date: 2020-05-03 22:16:30.865617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28a863470a67'
down_revision = 'b8b315b2018a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'dummy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('dummy', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
