"""update tables 4

Revision ID: 8a6a6b8c9472
Revises: ee57a16e25b9
Create Date: 2020-05-03 00:30:00.334243

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8a6a6b8c9472'
down_revision = 'ee57a16e25b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.drop_column('Shows', 'ddmyt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('ddmyt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('Shows', 'start_time')
    # ### end Alembic commands ###
