"""relationship shows and venue 8

Revision ID: b8b315b2018a
Revises: ed56f0baa572
Create Date: 2020-05-03 22:15:36.192732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8b315b2018a'
down_revision = 'ed56f0baa572'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('dummy', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'dummy')
    # ### end Alembic commands ###
