"""Add table and update 1

Revision ID: ed103618129e
Revises: a4cd723c61bb
Create Date: 2020-05-02 20:12:19.811772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed103618129e'
down_revision = 'a4cd723c61bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('genre', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Shows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('ddmyt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Artist', sa.Column('actively_seeking', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('requirement_message', sa.String(), nullable=True))
    op.add_column('Artist', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('actively_seeking', sa.Boolean(), nullable=True))
    op.add_column('Venue', sa.Column('requirement_message', sa.String(), nullable=True))
    op.add_column('Venue', sa.Column('website_link', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'website_link')
    op.drop_column('Venue', 'requirement_message')
    op.drop_column('Venue', 'actively_seeking')
    op.drop_column('Artist', 'website_link')
    op.drop_column('Artist', 'requirement_message')
    op.drop_column('Artist', 'actively_seeking')
    op.drop_table('Shows')
    op.drop_table('Genres')
    # ### end Alembic commands ###
