"""update tables 3

Revision ID: ee57a16e25b9
Revises: d4e544857ba5
Create Date: 2020-05-03 00:00:14.408166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee57a16e25b9'
down_revision = 'd4e544857ba5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_description', sa.String(), nullable=True))
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.drop_column('Artist', 'actively_seeking')
    op.drop_column('Artist', 'requirement_message')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('requirement_message', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Artist', sa.Column('actively_seeking', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'seeking_venue')
    op.drop_column('Artist', 'seeking_description')
    # ### end Alembic commands ###
